name: Odoo Module Tests

on:
  pull_request:
    branches:
      - production  # Trigger on PRs to production

jobs:
  odoo:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Run Odoo
        run: |
          /opt/odoo18/odoo18-venv/bin/python3 /opt/odoo18/odoo/odoo-bin --config=/etc/odoo18.conf -u base --stop-after-init
